# Discord Bot Settings
[discord]
token = "YOUR_DISCORD_BOT_TOKEN"
guild_id = "123456789012345678"

# Discord Channels ID
[discord.channels_id]
chat = "234567890123456789"

# Minecraft Bridge Settings
[minecraft]
enable_chat_bridge = true
chat_format = "<{username}> {message}"
discord_to_mc_format = "[Discord] {username}: {message}"
show_join_leave = true

# Webhook Settings
[webhook.formatting]
username_format = "{username}"
avatar_url = "https://mc-heads.net/avatar/{uuid}/64"

# Logging Settings
[logging]
log_to_file = true
log_file_path = "logs/bridge.log"